{% set name = "roaring-landmask" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gauteh/roaring-landmask/archive/refs/heads/geos311.zip
  sha256: 32b695a87b4fb08e92444634bfcf86823b48c34b2ce43d0594a437250530a145

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin                             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - libcxx     # [ win ]
    - vc14_runtime  # [ win ]
  host:
    - python
    - pip
    - maturin
    - pkg-config
  run:
    - python
    - libgcc-ng  # [ linux ]
    - libcxx     # [ osx ]
    - libcxx     # [ win ]
    - vc14_runtime  # [ win ]
    - xz

test:
  imports:
    - roaring_landmask
  commands:
    - pip check
    - python -c "from roaring_landmask import RoaringLandmask; l = RoaringLandmask.new(); assert l.contains(15., 65.6)"
  requires:
    - pip

about:
  home: https://github.com/gauteh/roaring-landmask
  summary: A fast and limited-memory structure with a landmask based on GSHHG for determing whether a point on Earth is on land or in the ocean
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gauteh
    - knutfrode
