{% set name = "roaring-landmask" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/roaring_landmask-{{ version }}.tar.gz
  sha256: 27b44a7004e6a25ee32e0fedc6b35936eb118aedb6187c237b8287255f7202ff

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin                             # [build_platform != target_platform]
    - {{ compiler('c') }}             # [ linux ]
    - {{ compiler('m2w64_c') }}       # [ win ]
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin
    - pkg-config
  run:
    - python
    - libgcc-ng  # [ linux ]
    - libcxx     # [ osx ]
    - libcxx     # [ win ]
    - xz

test:
  imports:
    - roaring_landmask
  commands:
    - pip check
    - python -c "from roaring_landmask import RoaringLandmask; l = RoaringLandmask.new(); assert l.contains(15., 65.6)"
  requires:
    - pip

about:
  home: https://github.com/gauteh/roaring-landmask
  summary: A fast and limited-memory structure with a landmask based on GSHHG for determing whether a point on Earth is on land or in the ocean
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gauteh
    - knutfrode
