{% set name = "roaring-landmask" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/roaring_landmask-{{ version }}.tar.gz
  sha256: 4801e3ca2be779553b9cca40cf64a6f1f2dae3e5dafb52a90b2ec9408ac9bad2

build:
  number: 0

requirements:
  build:
    - cmake<4
    - make
    - pkg-config
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin                             # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin
    - pkg-config
  run:
    - python
    - xz

test:
  imports:
    - roaring_landmask
  commands:
    - pip check
    - python -c "from roaring_landmask import RoaringLandmask; l = RoaringLandmask.new(); assert l.contains(15., 65.6)"
  requires:
    - pip

about:
  home: https://github.com/gauteh/roaring-landmask
  summary: A fast and limited-memory structure with a landmask based on GSHHG for determing whether a point on Earth is on land or in the ocean
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gauteh
    - knutfrode
