{% set name = "roaring-landmask" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/roaring_landmask-{{ version }}.tar.gz
  sha256: dddd74951ca1b01c624ac2973def602dad6c69cf5f40e9bd64bfac84bc820889

build:
  number: 1

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin                             # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - geos
  host:
    - python
    - pip
    - maturin
    - pkg-config
  run:
    - python
    - xz
    - geos

test:
  imports:
    - roaring_landmask
  commands:
    - pip check
    - python -c "from roaring_landmask import RoaringLandmask; l = RoaringLandmask.new(); assert l.contains(15., 65.6)"
  requires:
    - pip

about:
  home: https://github.com/gauteh/roaring-landmask
  summary: A fast and limited-memory structure with a landmask based on GSHHG for determing whether a point on Earth is on land or in the ocean
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gauteh
    - knutfrode
